# Generated by Django 4.0.4 on 2022-05-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='day',
            new_name='contactnumber',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='email',
            new_name='citizenshipnumber',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='password',
            new_name='contactnumber',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='method',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='email',
            new_name='contactnumber',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='player',
            name='password',
        ),
        migrations.RemoveField(
            model_name='player',
            name='phone',
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='duration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
    ]
