# Generated by Django 4.0.4 on 2022-05-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_name',
            new_name='player_Teamname',
        ),
    ]
