# Generated by Django 4.0.4 on 2022-06-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_player_name_player_player_teamname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booker_name',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='start_time',
            field=models.TextField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_Teamname',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='start_time',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
