# Generated by Django 4.0.4 on 2022-06-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_booking_booker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booker_name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
