# Generated by Django 4.0.4 on 2022-06-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_booking_booker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='price',
            field=models.IntegerField(default=True),
        ),
    ]
