# Generated by Django 4.0.4 on 2022-07-29 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='match',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.match'),
        ),
        migrations.AddField(
            model_name='payment',
            name='player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.player'),
        ),
    ]
